import { Board, Pin, User } from "@prisma/client";

export const dummyUsers: User[] = [
  {
    id: '1',
    name: 'Fell',
    username: "iyhmh",
    email: "fell@gmail.com",
    bio: 'Aku adalah dia, dia adalah aku',
    emailVerified: new Date(),
    password: "password",
    avatar: 'https://i.pinimg.com/564x/d5/3d/1a/d53d1a6aebfbf00229f533ca2d85eaa7.jpg',
    banner: 'https://i.pinimg.com/originals/c8/69/89/c86989504e0f90b5f48aad50ffc24376.jpg',
    birthday: new Date(2006, 7, 20),
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: 'male',
    privacy: 'public',
    region: "Japan",
    role: 'user',
  },
  {
    id: '2',
    name: 'Ranpang',
    username: "ranpang",
    email: "ranpang@gmail.com",
    bio: '',
    emailVerified: new Date(),
    password: "password",
    avatar: 'https://i.pinimg.com/564x/4d/41/dc/4d41dc25801d1e6f3d2a437d70db4214.jpg',
    banner: '',
    birthday: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: 'male',
    privacy: 'public',
    region: "Japan",
    role: 'user',
  },
  {
    id: '3',
    name: 'yudiyahrian',
    username: 'mikuchan006',
    email: 'wkwkland@gmail.com',
    bio: '1-7-21',
    emailVerified: new Date(),
    password: 'password',
    avatar: 'https://i.pinimg.com/736x/f3/bc/96/f3bc968c357b468c77096448f96a87db.jpg',
    banner: 'https://i.pinimg.com/736x/f7/76/48/f77648270c05c8b5a27f367be97e7b66.jpg',
    birthday: new Date(2005, 11, 26),
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: 'male',
    privacy: 'public',
    region: 'Japan',
    role: 'user'
  },
  {
    id: '4',
    name: 'otosakaell',
    username: 'else',
    email: 'fachrylord0@gmail.com',
    bio: 'wnna be ur vacuum cleaner',
    emailVerified: new Date(),
    password: 'password',
    avatar: 'https://i.pinimg.com/originals/a1/9b/ae/a19baeddae667c52b77d28f65c44b711.jpg',
    banner: 'https://i.pinimg.com/736x/f7/76/48/f77648270c05c8b5a27f367be97e7b66.jpg',
    birthday: new Date(2005, 10, 27),
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: 'male',
    privacy: 'public',
    region: 'Japan',
    role: 'user'
  },
  {
    id: '5',
    name: 'vrlstevnn',
    username: 'Varell',
    email: 'steven@gmail.com',
    bio: '',
    emailVerified: new Date(),
    password: 'password',
    avatar: 'https://i.pinimg.com/564x/0c/71/55/0c7155a2455c8637e34404c967904ee8.jpg',
    banner: 'https://i.pinimg.com/736x/f7/76/48/f77648270c05c8b5a27f367be97e7b66.jpg',
    birthday: new Date(2005, 5, 17),
    createdAt: new Date(),
    updatedAt: new Date(),
    gender: 'male',
    privacy: 'public',
    region: 'Japan',
    role: 'user'
  },
]

export const dummyPins = [
  {
    id: '1',
    user: dummyUsers[0],
    photos: ['https://i.pinimg.com/564x/aa/22/9d/aa229dde05694e15f088c172c5759c5f.jpg'],
    title: '',
    description: '',
    commentable: true,
    link: '',
    tags: [],
    privacy: 'public',
    Comment: [
      {
        id: '1',
        pinId: '1',
        userId: dummyUsers[0].id,
        replyToId: null,
        content: 'yahahah',
        createdAt: new Date(2020, 2, 1),
        updatedAt: new Date(2020, 2, 1),
        CommentLikes: [],
        replyTo: null,
        replies: [],
        User: dummyUsers[0]
      }
    ]
  },
  {
    id: '2',
    user: dummyUsers[1],
    photos: ['https://i.pinimg.com/564x/55/2f/d3/552fd3b4aaf7ab8756e1494eb3a505cb.jpg'],
    title: 'afternoon',
    description: '',
    commentable: true,
    link: 'https://docs.google.com/forms/d/e/1FAIpQLSfWIYDAUNCuEDGL_yPEinKME4K6nueUnT_c5vwmMqS1Q4-u7A/viewform',
    tags: [],
    privacy: 'public',
    Comment: []
  },
  {
    id: '3',
    user: dummyUsers[2],
    photos: ['https://i.pinimg.com/564x/9c/a3/29/9ca32982d5548f50cfcc25252abce38e.jpg'],
    title: '',
    description: '',
    commentable: true,
    link: '',
    tags: [],
    privacy: 'public',
    Comment: []
  },
  {
    id: '4',
    user: dummyUsers[3],
    photos: ['https://i.pinimg.com/564x/e1/ec/92/e1ec9214f81b3133621c5c43a3fb9757.jpg'],
    title: '',
    description: '',
    commentable: true,
    link:'https://tailwindcss.com/docs/responsive-design',
    tags: [],
    privacy: 'public',
    Comment: []
  },
  {
    id: '5',
    user: dummyUsers[4],
    photos: ['https://i.pinimg.com/564x/c5/9f/8c/c59f8c64dfdb6d681fca19a652b9d52d.jpg'],
    title: '',
    description: '',
    commentable: true,
    link: '',
    tags: [],
    privacy: 'public',
    Comment: []
  },
  {
    id: '6',
    user: dummyUsers[0],
    photos: ['https://i.pinimg.com/736x/84/02/f3/8402f39d79c6da9814d7efdf9533b9ed.jpg'],
    title: '',
    description: '',
    commentable: true,
    link: '',
    tags: [],
    privacy: 'public',
    Comment: []
  },
  {
    id: '7',
    user: dummyUsers[0],
    photos: ['https://i.pinimg.com/564x/0b/47/3c/0b473c264e5339724e5ad62fd3c0d940.jpg'],
    title: '',
    description: '',
    commentable: true,
    link: '',
    tags: [],
    privacy: 'public',
    Comment: []
  },
  {
    id: '8',
    user: dummyUsers[0],
    photos: ['https://i.pinimg.com/736x/e7/71/f6/e771f6581c14e35ed4e17fc81bf9312e.jpg'],
    title: '',
    description: '',
    commentable: true,
    link: '',
    tags: [],
    privacy: 'public',
    Comment: []
  },
  {
    id: '9',
    user: dummyUsers[0],
    photos: ['https://i.pinimg.com/564x/23/15/1e/23151e7f89de4f79b773abf2e648b3c2.jpg'],
    title: '',
    description: '',
    commentable: true,
    link: '',
    tags: [],
    privacy: 'public',
    Comment: []
  },
  {
    id: '10',
    user: dummyUsers[0],
    photos: ['https://i.pinimg.com/564x/2e/39/fd/2e39fda15778738e2c49891ed159c8d8.jpg'],
    title: '',
    description: '',
    commentable: true,
    link: '',
    tags: [],
    privacy: 'public',
    Comment: []
  },
  {
    id: '11',
    user: dummyUsers[2],
    photos: ['https://i.pinimg.com/originals/b7/61/72/b76172cdd8b6daf89761bfff6d71f6bf.jpg', 'https://i.pinimg.com/originals/2b/fe/ca/2bfeca9fd53c4fa9d07c94c99532e7a5.jpg', 'https://i.pinimg.com/originals/70/5e/3a/705e3a6eabae75ee1040391fda1d4381.jpg'],
    title: 'It will rain',
    description: '',
    commentable: true,
    link: '',
    tags: ['Frieren at the Funeral', 'frieren', 'Himmel/Frieren', 'フリー', 'furi-renn', 'sougetsusou', "Himmel (Frieren: Beyond Journey's End)", "hanabatakewodashumahou"],
    privacy: 'public',
    Comment: [
      {
        id: '1',
        pinId: '1',
        userId: dummyUsers[3].id,
        replyToId: null,
        content: 'yahahah',
        createdAt: new Date(2020, 2, 1),
        updatedAt: new Date(2020, 2, 1),
        CommentLikes: [],
        replyTo: null,
        replies: [],
        User: dummyUsers[3]
      },
      {
        id: '2',
        pinId: '1',
        userId: dummyUsers[2].id,
        replyToId: null,
        content: 'No more FF (Frieren Friday) 💔💔',
        createdAt: new Date(2020, 2, 1),
        updatedAt: new Date(2020, 2, 1),
        CommentLikes: [
          {
            id: '1',
            commentId: '2',
            userId: dummyUsers[3].id,
            isLiked: true,
            createdAt: new Date(),
            updatedAt: new Date(),
            User: dummyUsers[3],
          },
        ],
        replyTo: null,
        replies: [
          {
            id: '1',
            pinId: '1',
            userId: dummyUsers[0].id,
            replyToId: null,
            content: 'apalah',
            createdAt: new Date(2020, 2, 1),
            updatedAt: new Date(2020, 2, 1),
            CommentLikes: [],
            replyTo: null,
            replies: [],
            User: dummyUsers[0]
          }
        ],
        User: dummyUsers[2]
      },
    ]
  },
]

export const dummyAlbums = [
  {
    id: '1',
    name: 'rndm',
    description: 'jst a rndm thngs',
    privacy: 'public',
    userId: dummyUsers[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
    User: dummyUsers[0],
    Pins: dummyPins.slice(0, 3)
  },
  {
    id: '2',
    name: 'hm',
    description: 'jst a rndm thngs',
    privacy: 'private',
    userId: dummyUsers[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
    User: dummyUsers[0],  
    Pins: dummyPins.slice(2, 6)
  },
  {
    id: '2',
    name: 'hm',
    description: '',
    privacy: 'private',
    userId: dummyUsers[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
    User: dummyUsers[0],  
    Pins: dummyPins.slice(2, 6)
  },
  {
    id: '2',
    name: 'hm',
    description: '',
    privacy: 'private',
    userId: dummyUsers[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
    User: dummyUsers[0],  
    Pins: dummyPins.slice(2, 6)
  },
  {
    id: '2',
    name: 'hm',
    description: '',
    privacy: 'private',
    userId: dummyUsers[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
    User: dummyUsers[0],  
    Pins: dummyPins.slice(2, 6)
  },
  {
    id: '2',
    name: 'hm',
    description: '',
    privacy: 'private',
    userId: dummyUsers[0].id,
    createdAt: new Date(),
    updatedAt: new Date(),
    User: dummyUsers[0],  
    Pins: dummyPins.slice(2, 6)
  },
]